spring:
  application:
    name: forjun

  datasource:
    url: jdbc:postgresql://localhost:5432/forjun
    username: sijun
    password: sijun
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true # 실행되는 SQL 쿼리를 출력
    properties:
      hibernate:
        format_sql: true # 출력된 SQL을 포맷팅하여 보기 쉽게 함
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # 데이터베이스에 맞는 다이얼렉트 설정

    hibernate:
      ddl-auto: update # 옵션: none, validate, update, create, create-drop

server:
  port: 8085

jwt:
  secretKey: eab1c4a71659aeb5fa6f913f7021b9a5e3c9d2d0c4f4e12bd4bcf88712a73c43

logging:
  level:
      org:
        springframework:
          web: TRACE

        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql: TRACE
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

file:
  upload:
    # 💡 파일이 저장될 서버의 로컬 경로 (예: 프로젝트 루트/.upload)
    local-dir: ./uploads
    # 💡 파일에 접근할 때 사용할 기본 URL (개발 환경에서는 보통 서버 IP:Port/api 경로)
    base-url: http://localhost:8080/api/files/download/


